language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm
    - hhvm-nightly

before_script:
    - composer install --no-dev

script: phpunit -c tests/phpunit.xml

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly

