language: php

php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

before_script:
    - curl -s http://getcomposer.org/installer | php -- --quiet
    - php composer.phar install

script: ./vendor/bin/phpunit -c tests/phpunit.xml

matrix:
    allow_failures:
        - php: 5.3.3
        - php: 7
        - php: hhvm

branches:
    only:
        - master